using System.Reflection;
using Asp.Versioning.ApiExplorer;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace EcoTracker.Core.Swagger.Data
{
    public class SwaggerOptions : IConfigureOptions<SwaggerGenOptions>
    {
        private readonly IApiVersionDescriptionProvider _apiVersionDescriptionProvider;
        private readonly IConfiguration _configuration;

        public SwaggerOptions(IConfiguration configuration, IOC ioc)
        {
            _configuration = configuration;
            _apiVersionDescriptionProvider = ioc.GetService<IApiVersionDescriptionProvider>();
        }

        public void Configure(SwaggerGenOptions options)
        {
            IncludeXmlComments(options);
            MapApiVersionsToSwaggerDoc(options);

            // add JWT Authentication
            var securityScheme = new OpenApiSecurityScheme
            {
                Name = "JWT Authentication",
                Description = "Enter JWT Bearer token **_only_**",
                In = ParameterLocation.Header,
                Type = SecuritySchemeType.Http,
                Scheme = "bearer", // must be lower case
                BearerFormat = "JWT",
                Reference = new OpenApiReference
                {
                    Id = JwtBearerDefaults.AuthenticationScheme,
                    Type = ReferenceType.SecurityScheme
                }
            };
            options.AddSecurityDefinition(securityScheme.Reference.Id, securityScheme);
            options.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {securityScheme, new string[] { }}
                });

            options.OperationFilter<SwaggerDefaultValues>();
        }

        private void MapApiVersionsToSwaggerDoc(SwaggerGenOptions options)
        {
            if (_apiVersionDescriptionProvider != null)
            {
                foreach (var description in _apiVersionDescriptionProvider.ApiVersionDescriptions)
                    options.SwaggerDoc($"{description.GroupName}", GetOpenApiInfo(description.GroupName.ToUpperInvariant()));

                return;
            }
            else
                options.SwaggerDoc("v1", GetOpenApiInfo("V1"));
        }

        private void IncludeXmlComments(SwaggerGenOptions options)
        {
            try
            {
                var xmlFile = $"{Assembly.GetEntryAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                options.IncludeXmlComments(xmlPath);
            }
            catch (Exception) { }
        }

        private OpenApiInfo GetOpenApiInfo(string version) => new OpenApiInfo()
        {
            Title = _configuration["Swagger:Title"] ?? Assembly.GetEntryAssembly().GetName().Name,
            Description = $"\r\n{_configuration["Swagger:Description"]}\r\n" +
                          $"\r\n*Auto generated by [Swagger UI](https://swagger.io/tools/swagger-ui/)*\r\n" +
                          $"\r\nExecution Date (UTC): {ProgramInfo.ExecutionDate:dd/MM/yyyy HH:mm:ss} \r\n" +
                          $"\r\nExecution Id: {ProgramInfo.ExecutionId} \r\n" +
                          $"\r\nThis API is intended for private consumption over dedicated links.",
            Version = version
        };

        public class SwaggerDefaultValues : IOperationFilter
        {
            public void Apply(OpenApiOperation operation, OperationFilterContext context)
            {
                var apiDescription = context.ApiDescription;

                operation.Deprecated = apiDescription.IsDeprecated();

                if (operation.Parameters is null) return;

                foreach (var parameter in operation.Parameters.OfType<OpenApiRequestBody>())
                {
                    var description = apiDescription.ParameterDescriptions.First(p => p.Name == parameter.Description);

                    if (parameter.Description is null)
                        parameter.Description = description.ModelMetadata?.Description;

                    parameter.Required |= description.IsRequired;
                }
            }
        }
    }
}
